### ISSUE TITLE
Research failure in logs

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/krihelinator#134]
Failure 1:

```
18:20:18.395 [error] Ranch protocol #PID<0.28926.18> (:cowboy_protocol) of listener Krihelinator.Endpoint.HTTP terminated
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :cow_http_hd.token_ci_list_sep/3
        (cowlib) src/cow_http_hd.erl:191: :cow_http_hd.token_ci_list_sep("Te", [], "keep-alive")
        (cowlib) src/cow_http_hd.erl:31: :cow_http_hd.parse_connection/1
        (cowboy) src/cowboy_req.erl:189: :cowboy_req.new/14
        (cowboy) src/cowboy_protocol.erl:410: :cowboy_protocol.request/9
```

Failure 2:

```
00:37:25.542 [error] GenServer :tzdata_release_updater terminating
** (ArgumentError) argument error
    :erlang.hd([])
    (tzdata) lib/tzdata/data_loader.ex:29: Tzdata.DataLoader.content_length_from_headers/1
    (tzdata) lib/tzdata/data_loader.ex:51: Tzdata.DataLoader.do_latest_file_size/1
    (tzdata) lib/tzdata/release_updater.ex:48: Tzdata.ReleaseUpdater.loaded_tzdata_matches_iana_file_size?/0
    (tzdata) lib/tzdata/release_updater.ex:36: Tzdata.ReleaseUpdater.poll_for_update/0
    (tzdata) lib/tzdata/release_updater.ex:17: Tzdata.ReleaseUpdater.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
Last message: :check_if_time_to_update
```

Note that they don't have critical effect on the system.

**Comment by Nagasaki45** [comment]
The tzdata issue is probably due to old version. I need to upgrade it. [More info](https://github.com/lau/tzdata/issues/9#issuecomment-285020450).

**Comment by Nagasaki45** [comment]
Copied the cowboy issue to another ticket to close this one...
