### ISSUE TITLE
Server error when GETting "/repositories/"

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/krihelinator#140]
```
20:17:45.155 [error] #PID<0.663.0> running Krihelinator.Endpoint terminated
Server: krihelinator.xyz:80 (http)
Request: GET /repositories/
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        (krihelinator) lib/scraper.ex:36: Krihelinator.Scraper.combine_full_name/1
        (krihelinator) web/controllers/helpers.ex:13: Krihelinator.Controllers.Helpers.get_from_db_or_scrape/1
        (krihelinator) web/controllers/page_controller.ex:14: Krihelinator.PageController.repository/2
        (krihelinator) web/controllers/page_controller.ex:1: Krihelinator.PageController.action/2
        (krihelinator) web/controllers/page_controller.ex:1: Krihelinator.PageController.phoenix_controller_pipeline/2
        (krihelinator) lib/krihelinator/endpoint.ex:1: Krihelinator.Endpoint.instrument/4
        (krihelinator) lib/phoenix/router.ex:261: Krihelinator.Router.dispatch/2
        (krihelinator) web/router.ex:1: Krihelinator.Router.do_call/2
```

**Comment by Nagasaki45** [comment]
Or "/repositories/Ada".
