### ISSUE TITLE
Scraping error in the logs

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/krihelinator#142]
Needs investigation. The impact is unclear.
```
02:53:45.066 [error] Task #PID<0.29446.15> started from #PID<0.28603.15> terminating
** (MatchError) no match of right hand side value: :error
    (krihelinator) lib/scraper.ex:36: Krihelinator.Scraper.combine_full_name/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [&Krihelinator.Scraper.scrape_repo/1, [#Ecto.Changeset<action: nil, changes: %{dirty: false}, errors: [], data: #Krihelinator.GithubRepo<>, valid?: true>]]
```

**Comment by Nagasaki45** [comment]
Can't see this issue anymore, good chances that it was already fixed. Cosing.
