### ISSUE TITLE
Consider handling BigQuery cache hits

### ISSUE THREAD

**Issue by Nagasaki45** [Nagasaki45/krihelinator#168]
```
[info] Getting repositories from BigQuery to scrape
[error] Task #PID<0.16224.17> started from Quantum terminating
** (MatchError) no match of right hand side value: {:ok, %BigQuery.Types.QueryResultsResponse{cacheHit: nil, errors: [], etag: nil, jobComplete: false, jobReference: %BigQuery.Types.JobReference{jobId: "job__Ut3c6Kald9SMf0leTVZ0Va0nNo", projectId: "krihelinator"}, kind: "bigquery#queryResponse", pageToken: nil, rows: [], schema: nil, totalBytesProcessed: nil, totalRows: nil}}
    (krihelinator) lib/krihelinator/periodic/big_query.ex:11: Krihelinator.Periodic.BigQuery.query/0
    (krihelinator) lib/krihelinator/periodic.ex:75: Krihelinator.Periodic.scrape_from_bigquery/0
    (krihelinator) lib/krihelinator/periodic.ex:41: Krihelinator.Periodic.run/0
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Quantum.Executor.execute/2
    Args: [{~e[0 */6 * * * *], {Krihelinator.Periodic, :run}, [], :utc}, %{d: {2017, 4, 27}, h: 0, jobs: [keep_languages_history: %Quantum.Job{args: [], name: :keep_languages_history, nodes: [:"krihelinator@127.0.0.1"], overlap: false, pid: #PID<0.16231.17>, schedule: ~e[0 5 */3 * * *], state: :active, task: {Krihelinator.History, :keep_languages_history}, timezone: :utc}, periodic: %Quantum.Job{args: [], name: :periodic, nodes: [:"krihelinator@127.0.0.1"], overlap: false, pid: #PID<0.16234.17>, schedule: ~e[0 */6 * * * *], state: :active, task: {Krihelinator.Periodic, :run}, timezone: :utc}], m: 0, r: 0, s: 0, w: 4}]
=CRASH REPORT==== 27-Apr-2017::00:00:14 ===
  crasher:
    initial call: Elixir.Quantum.Executor:execute/2
    pid: <0.16224.17>
    registered_name: []
    exception exit: {{badmatch,
                         {ok,#{'__struct__' =>
                                   'Elixir.BigQuery.Types.QueryResultsResponse',
                               cacheHit => nil,errors => [],etag => nil,
                               jobComplete => false,
                               jobReference =>
                                   #{'__struct__' =>
                                         'Elixir.BigQuery.Types.JobReference',
                                     jobId =>
                                         <<"job__Ut3c6Kald9SMf0leTVZ0Va0nNo">>,
                                     projectId => <<"krihelinator">>},
                               kind => <<"bigquery#queryResponse">>,
                               pageToken => nil,rows => [],schema => nil,
                               totalBytesProcessed => nil,totalRows => nil}}},
                     [{'Elixir.Krihelinator.Periodic.BigQuery',query,0,
                          [{file,"lib/krihelinator/periodic/big_query.ex"},
                           {line,11}]},
                      {'Elixir.Krihelinator.Periodic',scrape_from_bigquery,0,
                          [{file,"lib/krihelinator/periodic.ex"},{line,75}]},
                      {'Elixir.Krihelinator.Periodic',run,0,
                          [{file,"lib/krihelinator/periodic.ex"},{line,41}]},
                      {'Elixir.Task.Supervised',do_apply,2,
                          [{file,"lib/task/supervised.ex"},{line,85}]},
                      {'Elixir.Task.Supervised',reply,5,
                          [{file,"lib/task/supervised.ex"},{line,36}]},
                      {proc_lib,init_p_do_apply,3,
                          [{file,"proc_lib.erl"},{line,247}]}]}
      in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 116)
      in call from 'Elixir.Task.Supervised':reply/5 (lib/task/supervised.ex, line 36)
    ancestors: [quantum_tasks_sup,'Elixir.Quantum.Supervisor',<0.1790.0>]
    messages: []
    links: [<0.1792.0>,<0.16237.17>,<0.1771.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 46422
    stack_size: 27
    reductions: 1018832
  neighbours:
    neighbour: [{pid,<0.16237.17>},
                  {registered_name,[]},
                  {initial_call,
                      {'Elixir.Krihelinator.Periodic','-run/0-fun-0-',[]}},
                  {current_function,{'Elixir.Process',sleep,1}},
                  {ancestors,
                      [<0.16224.17>,quantum_tasks_sup,
                       'Elixir.Quantum.Supervisor',<0.1790.0>]},
                  {messages,[]},
                  {links,[<0.16224.17>]},
                  {dictionary,[]},
                  {trap_exit,false},
                  {status,waiting},
                  {heap_size,233},
                  {stack_size,13},
                  {reductions,21}]
=SUPERVISOR REPORT==== 27-Apr-2017::00:00:14 ===
     Supervisor: {local,quantum_tasks_sup}
     Context:    child_terminated
     Reason:     {{badmatch,
                      {ok,#{'__struct__' =>
                                'Elixir.BigQuery.Types.QueryResultsResponse',
                            cacheHit => nil,errors => [],etag => nil,
                            jobComplete => false,
                            jobReference =>
                                #{'__struct__' =>
                                      'Elixir.BigQuery.Types.JobReference',
                                  jobId =>
                                      <<"job__Ut3c6Kald9SMf0leTVZ0Va0nNo">>,
                                  projectId => <<"krihelinator">>},
                            kind => <<"bigquery#queryResponse">>,
                            pageToken => nil,rows => [],schema => nil,
                            totalBytesProcessed => nil,totalRows => nil}}},
                  [{'Elixir.Krihelinator.Periodic.BigQuery',query,0,
                       [{file,"lib/krihelinator/periodic/big_query.ex"},
                        {line,11}]},
                   {'Elixir.Krihelinator.Periodic',scrape_from_bigquery,0,
                       [{file,"lib/krihelinator/periodic.ex"},{line,75}]},
                   {'Elixir.Krihelinator.Periodic',run,0,
                       [{file,"lib/krihelinator/periodic.ex"},{line,41}]},
                   {'Elixir.Task.Supervised',do_apply,2,
                       [{file,"lib/task/supervised.ex"},{line,85}]},
                   {'Elixir.Task.Supervised',reply,5,
                       [{file,"lib/task/supervised.ex"},{line,36}]},
                   {proc_lib,init_p_do_apply,3,
                       [{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.16224.17>},
                  {id,'Elixir.Task.Supervised'},
                  {mfargs,{'Elixir.Task.Supervised',start_link,undefined}},
                  {restart_type,temporary},
                  {shutdown,5000},
                  {child_type,worker}]
```

**Comment by Nagasaki45** [comment]
Not really necessary when I'm not messing around too much with the dev environment. Closing
